config/routes.rb
ContactInquiry::Application.routes.draw do
  resources :contact_forms

end

app/models/contact_form.rb
class ContactForm < ActiveRecord::Base
  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :subject
  validates_presence_of :description

  validates_format_of :email, :with =>
  /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contact_forms_controller.rb
class ContactFormsController < ApplicationController
  before_action :set_contact_form, only: [:show, :edit, :update, :destroy]

  # GET /contact_forms
  # GET /contact_forms.json
  def index
    @contact_forms = ContactForm.all
  end

  # GET /contact_forms/1
  # GET /contact_forms/1.json
  def show
  end

  # GET /contact_forms/new
  def new
    @contact_form = ContactForm.new
  end

  # GET /contact_forms/1/edit
  def edit
  end

  # POST /contact_forms
  # POST /contact_forms.json
  def create
    @contact_form = ContactForm.new(contact_form_params)

    respond_to do |format|
      if @contact_form.save
        format.html { redirect_to @contact_form, notice: 'Contact form was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact_form }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_forms/1
  # PATCH/PUT /contact_forms/1.json
  def update
    respond_to do |format|
      if @contact_form.update(contact_form_params)
        format.html { redirect_to @contact_form, notice: 'Contact form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_forms/1
  # DELETE /contact_forms/1.json
  def destroy
    @contact_form.destroy
    respond_to do |format|
      format.html { redirect_to contact_forms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_form
      @contact_form = ContactForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_form_params
      params.require(:contact_form).permit(:email, :last_name, :first_name, :subject, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_forms_helper.rb
module ContactFormsHelper
end

app/views/contact_forms/_form.html.erb
<%= form_for(@contact_form) do |f| %>
  <% if @contact_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_form.errors.count, "error") %> prohibited this contact_form from being saved:</h2>

      <ul>
      <% @contact_form.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_forms/edit.html.erb
<h1>Editing contact_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_form %> |
<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/index.html.erb
<h1>Listing contact_forms</h1>

<%= "#{@contact_forms.count} inquiries" %>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Last name</th>
      <th>First name</th>
      <th>Subject</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_forms.each do |contact_form| %>
      <tr>
        <td><%= contact_form.email %></td>
        <td><%= contact_form.last_name %></td>
        <td><%= contact_form.first_name %></td>
        <td><%= contact_form.subject %></td>
        <td><%= contact_form.description %></td>
        <td><%= link_to 'Show', contact_form %></td>
        <td><%= link_to 'Edit', edit_contact_form_path(contact_form) %></td>
        <td><%= link_to 'Destroy', contact_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact form', new_contact_form_path %>

app/views/contact_forms/new.html.erb
<h1>New contact_form</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_forms_path %>

app/views/contact_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @contact_form.email %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @contact_form.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @contact_form.first_name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @contact_form.subject %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contact_form.description %>
</p>

<%= link_to 'Edit', edit_contact_form_path(@contact_form) %> |
<%= link_to 'Back', contact_forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactInquiry</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>